#!/usr/bin/env python3
"""C4-E1a: Arb certificate for the first positive-volume chart overlap.

The chart centres and frames are frozen binary64 data generated by the C4-E0
mixed trajectory.  All membership, projective-denominator, Jacobian, Neumann,
response, gradient, and local-residence bounds on the declared 14D overlap
box are evaluated with 256-bit outward-rounded Arb/Acb arithmetic.

This certifies a positive-volume overlap subbox and a positive local residence
window in each adjacent chart.  It does not certify that a nonzero flowpipe is
transported into that subbox, and therefore is not yet a continuation theorem.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import platform
import sys
from pathlib import Path

import numpy as np

try:
    import c4_arb_recovery_core_certificate_v1_0 as base
    import c4_arb_affine_taylor_subdivision_v1_2 as engine
    import c4_arb_quadratic_taylor_defect_v1_4 as quadratic_engine
    import c4_e0_moving_chart_overlap_preflight_v1_0 as e0
except ModuleNotFoundError as exc:
    raise RuntimeError(
        "Place this script beside the C4-B/D1/E0 modules and install "
        "python-flint==0.8.0 and numpy==2.0.2."
    ) from exc


TITLE = "C4-E1a ARB FIRST MOVING-CHART OVERLAP CERTIFICATE"
VERSION = "1.0"
DEFAULT_REPORT = "c4_e1a_arb_first_chart_overlap_certificate_v1_0.json"


def canonical_sha(value: object) -> str:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def exact(x: float):
    return base.exact_float(float(x))


def upper_abs(x) -> float:
    return float(base.upper(abs(x)))


def record(x) -> dict:
    return {
        "ball": str(x),
        "lower": float(base.lower(x)),
        "upper": float(base.upper(x)),
    }


def frozen_frame(model, theta: np.ndarray) -> dict:
    state = e0.geometry(model, theta, base.BETA)
    frame = np.column_stack((state["tangent"], state["normal"]))
    jacobian = state["jacobian"]
    right_inverse = jacobian.T @ np.linalg.inv(jacobian @ jacobian.T)
    return {
        "centre": np.asarray(theta, dtype=float).copy(),
        "tangent": state["tangent"].copy(),
        "normal": state["normal"].copy(),
        "frame": frame,
        "right_inverse": right_inverse,
        "minimum_singular_value": float(state["singular"][-1]),
    }


def frozen_mixed_charts(model, windows: int = 8, steps: int = 4) -> list[dict]:
    reference, tangent, normal = e0.deterministic_directions(model, 20260809)
    theta = reference + 2.5e-5 / math.sqrt(2.0) * (tangent + normal)
    charts = []
    for index in range(windows + 1):
        chart = frozen_frame(model, theta)
        chart["index"] = index
        charts.append(chart)
        if index < windows:
            theta, _ = e0.integrate_window(model, theta, 2.5e-5, steps, base.BETA)
    return charts


def configure_interval_engine() -> None:
    engine.NV = base.NPHASE
    quadratic_engine.NV = base.NPHASE
    engine.Affine = quadratic_engine.Quadratic


def ambient_phase_forms(centre: np.ndarray, frame: np.ndarray, half: np.ndarray):
    forms = []
    for phase in range(base.NPHASE):
        coefficients = [exact(frame[phase, j]) * exact(half[j])
                        for j in range(base.NPHASE)]
        forms.append(engine.Affine(exact(centre[phase]), coefficients))
    return forms


def jacobian_response_gradient(forms):
    z, dz, den_q = engine.projective_affine(forms, False)
    zb, dzb, denb_q = engine.projective_affine(forms, True)
    jacobian = [[base.arb(0) for _ in range(base.NPHASE)]
                for _ in range(base.RESPONSE_DIM)]
    for order in range(4):
        for phase in range(base.NPHASE):
            real = (dz[phase].c[order] + dzb[phase].c[order]) / 2
            imag = (dz[phase].c[order] - dzb[phase].c[order]) / base.acb(0, 2)
            jacobian[order][phase] = real.enclosure().real
            jacobian[4 + order][phase] = imag.enclosure().real

    z0, _ = base.projective_float(base.REFERENCE_PHASES, False)
    response_error = []
    for order in range(4):
        response_error.append(
            z.c[order].enclosure().real - exact(z0.c[order].real)
        )
    for order in range(4):
        response_error.append(
            z.c[order].enclosure().imag - exact(z0.c[order].imag)
        )

    product = z * zb
    denominator = 1 + product
    gradients = []
    for phase in range(base.NPHASE):
        derivative_product = dz[phase] * zb + z * dzb[phase]
        value = derivative_product / (denominator * denominator)
        gradients.append(value.c[6].enclosure().real)

    return {
        "jacobian": jacobian,
        "response_error": response_error,
        "gradients": gradients,
        "den": den_q.enclosure(),
        "denb": denb_q.enclosure(),
    }


def arb_matrix(values: np.ndarray):
    return [[exact(value) for value in row] for row in values]


def defect_bound(jacobian, right_inverse: np.ndarray):
    product = base.matmul(jacobian, arb_matrix(right_inverse))
    defect = [[
        (base.arb(1) if i == j else base.arb(0)) - product[i][j]
        for j in range(base.RESPONSE_DIM)
    ] for i in range(base.RESPONSE_DIM)]
    q, rows = base.inf_norm(defect)
    return q, rows


def coordinate_membership(
    ambient_centre: np.ndarray,
    ambient_frame: np.ndarray,
    ambient_half: np.ndarray,
    chart: dict,
    chart_half: np.ndarray,
) -> dict:
    margins = []
    centre_coordinates = []
    coordinate_radii = []
    for i in range(base.NPHASE):
        centre_coordinate = sum(
            (exact(chart["frame"][phase, i])
             * (exact(ambient_centre[phase]) - exact(chart["centre"][phase]))
             for phase in range(base.NPHASE)),
            base.arb(0),
        )
        radius = base.arb(0)
        for j in range(base.NPHASE):
            frame_coefficient = sum(
                (exact(chart["frame"][phase, i])
                 * exact(ambient_frame[phase, j])
                 for phase in range(base.NPHASE)),
                base.arb(0),
            )
            radius += abs(frame_coefficient) * exact(ambient_half[j])
        used = abs(centre_coordinate) + radius
        margin = exact(chart_half[i]) - used
        centre_coordinates.append(centre_coordinate)
        coordinate_radii.append(radius)
        margins.append(margin)
    return {
        "minimum_margin_lower": min(float(base.lower(x)) for x in margins),
        "maximum_coordinate_radius_upper": max(
            float(base.upper(x)) for x in coordinate_radii
        ),
        "all_coordinates_strictly_inside": all(base.lower(x) > 0 for x in margins),
    }


def speed_and_residence(data: dict, q_upper: float, right_inverse: np.ndarray,
                        beta: float, minimum_half: float) -> dict:
    response_inf = max(upper_abs(x) for x in data["response_error"])
    gradient_inf = max(upper_abs(x) for x in data["gradients"])
    y_frobenius = math.sqrt(sum(float(x) ** 2 for x in right_inverse.ravel()))
    if not (math.isfinite(q_upper) and q_upper < 1):
        return {
            "response_error_inf_upper": response_inf,
            "objective_gradient_inf_upper": gradient_inf,
            "field_speed_2_upper": math.inf,
            "local_residence_time_lower": None,
        }
    inverse_2 = math.sqrt(base.RESPONSE_DIM) / (1.0 - q_upper)
    pseudoinverse_2 = y_frobenius * inverse_2
    tangent_speed = math.sqrt(base.NPHASE) * gradient_inf
    recovery_speed = (
        beta * pseudoinverse_2 * math.sqrt(base.RESPONSE_DIM) * response_inf
    )
    speed = tangent_speed + recovery_speed
    residence = 0.5 * minimum_half / speed if speed > 0 else None
    return {
        "response_error_inf_upper": response_inf,
        "objective_gradient_inf_upper": gradient_inf,
        "right_inverse_frobenius": y_frobenius,
        "JY_inverse_2_upper": inverse_2,
        "moore_penrose_inverse_2_upper": pseudoinverse_2,
        "tangent_field_2_upper": tangent_speed,
        "recovery_field_2_upper": recovery_speed,
        "field_speed_2_upper": speed,
        "local_residence_time_lower": residence,
    }


def certify_transition(
    old: dict,
    new: dict,
    chart_tangent_half: float,
    chart_normal_half: float,
    overlap_tangent_half: float,
    overlap_normal_half: float,
    beta: float,
) -> dict:
    configure_interval_engine()
    ambient_centre = 0.5 * (old["centre"] + new["centre"])
    ambient_frame = old["frame"]
    ambient_half = np.r_[
        np.full(old["tangent"].shape[1], overlap_tangent_half),
        np.full(old["normal"].shape[1], overlap_normal_half),
    ]
    chart_half = np.r_[
        np.full(old["tangent"].shape[1], chart_tangent_half),
        np.full(old["normal"].shape[1], chart_normal_half),
    ]
    old_membership = coordinate_membership(
        ambient_centre, ambient_frame, ambient_half, old, chart_half
    )
    new_membership = coordinate_membership(
        ambient_centre, ambient_frame, ambient_half, new, chart_half
    )
    forms = ambient_phase_forms(ambient_centre, ambient_frame, ambient_half)
    data = jacobian_response_gradient(forms)
    q_old, _ = defect_bound(data["jacobian"], old["right_inverse"])
    q_new, _ = defect_bound(data["jacobian"], new["right_inverse"])
    q_old_upper = upper_abs(q_old)
    q_new_upper = upper_abs(q_new)
    speed = speed_and_residence(
        data, q_new_upper, new["right_inverse"], beta,
        min(overlap_tangent_half, overlap_normal_half),
    )
    den_lower = float(base.lower(abs(data["den"])))
    denb_lower = float(base.lower(abs(data["denb"])))
    log10_volume = base.NPHASE * math.log10(2.0) + sum(
        math.log10(float(x)) for x in ambient_half
    )
    gates = {
        "positive_volume_overlap_box": bool(all(x > 0 for x in ambient_half)),
        "overlap_box_strictly_inside_old_chart": bool(
            old_membership["all_coordinates_strictly_inside"]
        ),
        "overlap_box_strictly_inside_new_chart": bool(
            new_membership["all_coordinates_strictly_inside"]
        ),
        "projective_denominators_exclude_zero": bool(
            den_lower > 0 and denb_lower > 0
        ),
        "old_chart_uniform_neumann_defect_below_one": bool(q_old_upper < 1),
        "new_chart_uniform_neumann_defect_below_one": bool(q_new_upper < 1),
        "strictly_positive_new_chart_local_residence": bool(
            speed["local_residence_time_lower"] is not None
            and speed["local_residence_time_lower"] > 0
        ),
    }
    return {
        "transition": [int(old["index"]), int(new["index"])],
        "frozen_centres": {
            "old": old["centre"].tolist(),
            "new": new["centre"].tolist(),
            "overlap_midpoint": ambient_centre.tolist(),
        },
        "overlap_box": {
            "frame": "old frozen orthonormal SVD frame",
            "tangent_coordinate_half_width": overlap_tangent_half,
            "normal_coordinate_half_width": overlap_normal_half,
            "log10_volume": log10_volume,
        },
        "bounds": {
            "old_chart_membership": old_membership,
            "new_chart_membership": new_membership,
            "forward_projective_denominator_abs_lower": den_lower,
            "mirror_projective_denominator_abs_lower": denb_lower,
            "old_chart_neumann_defect_inf_upper": q_old_upper,
            "new_chart_neumann_defect_inf_upper": q_new_upper,
            "old_centre_minimum_singular_value": old["minimum_singular_value"],
            "new_centre_minimum_singular_value": new["minimum_singular_value"],
            **speed,
        },
        "gates": gates,
        "all_gates_pass": all(gates.values()),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chart-tangent-half", type=float, default=0.02)
    parser.add_argument("--chart-normal-half", type=float, default=1.0e-4)
    parser.add_argument("--overlap-tangent-half", type=float, default=1.0e-7)
    parser.add_argument("--overlap-normal-half", type=float, default=1.0e-7)
    parser.add_argument("--beta", type=float, default=base.BETA)
    parser.add_argument("--report", default=DEFAULT_REPORT)
    args, unknown = parser.parse_known_args(argv)
    if unknown:
        print("[notice] ignored notebook/kernel arguments:", unknown)
    if min(args.chart_tangent_half, args.chart_normal_half,
           args.overlap_tangent_half, args.overlap_normal_half, args.beta) <= 0:
        raise ValueError("all half-widths and beta must be positive")

    base.ctx.prec = base.PRECISION_BITS
    model_path = Path.cwd() / e0.MODEL_NAME
    model = e0.load_model(e0.obtain_model(Path.cwd()))
    charts = frozen_mixed_charts(model)
    protocol = {
        "version": VERSION,
        "precision_bits": base.PRECISION_BITS,
        "model_sha256": e0.MODEL_SHA256,
        "trajectory": "C4-E0 frozen mixed trajectory",
        "transition": [0, 1],
        "chart_tangent_half": args.chart_tangent_half,
        "chart_normal_half": args.chart_normal_half,
        "overlap_tangent_half": args.overlap_tangent_half,
        "overlap_normal_half": args.overlap_normal_half,
        "beta": args.beta,
        "criterion": "positive 14D overlap box inside both charts; Arb regularity in both charts",
    }
    print("=" * 100)
    print(f"{TITLE} v{VERSION}")
    print("=" * 100)
    print("scope: rigorous first overlap subbox; not flowpipe transport/global/K=1/QPU")
    print("protocol sha256:", canonical_sha(protocol))
    transition = certify_transition(
        charts[0], charts[1], args.chart_tangent_half, args.chart_normal_half,
        args.overlap_tangent_half, args.overlap_normal_half, args.beta,
    )
    passed = bool(transition["all_gates_pass"])
    status = (
        "C4_E1A_FIRST_POSITIVE_VOLUME_CHART_OVERLAP_CERTIFIED"
        if passed else "C4_E1A_INCONCLUSIVE"
    )
    result = {
        "title": TITLE,
        "version": VERSION,
        "protocol": protocol,
        "protocol_sha256": canonical_sha(protocol),
        "transition_certificate": transition,
        "all_gates_pass": passed,
        "scientific_status": status,
        "claim_boundary": (
            "A 256-bit outward-rounded positive-volume overlap subbox is "
            "certified inside the first two frozen moving charts, with uniform "
            "regularity and a positive local residence window. No validated "
            "flowpipe transport into the overlap box is proved."
        ),
        "required_next_step": (
            "C4-E2a may certify the eight-transition atlas overlap chain. "
            "A later validated-flowpipe handoff is required for a genuine "
            "finite moving-chart continuation theorem."
        ),
        "environment": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "python_flint": "0.8.0-compatible",
        },
    }
    Path(args.report).write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps({
        "bounds": transition["bounds"],
        "gates": transition["gates"],
        "all_gates_pass": passed,
        "scientific_status": status,
    }, indent=2))
    print("report:", args.report)
    return 0 if passed else 2


if __name__ == "__main__":
    code = main()
    if "ipykernel" not in sys.modules and "google.colab" not in sys.modules:
        raise SystemExit(code)
